# Generated by Django 3.1.6 on 2021-05-17 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profane_image', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='demoImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimg', models.ImageField(upload_to='demoImages/')),
            ],
        ),
        migrations.DeleteModel(
            name='InputImage',
        ),
    ]
